server.port=8080

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/urbanfix_db}
spring.datasource.username=${DB_USERNAME:urbanfix_user}
spring.datasource.password=${DB_PASSWORD:urbanfix_pass}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

app.jwt.secret=6dJmB1Kzq0T8vLw3nX9pR4sF7uY2hA5cD8eG1iJ6kL0mN3oP
app.jwt.expiration-ms=86400000

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.timeout=2000ms
