INSERT INTO public.expert_expertise (expert_profile_id,expertise) VALUES
	 (61,'Plumbing,Drainage,Pipe Repair'),
	 (62,'Electrical,Wiring,Appliance Repair'),
	 (63,'Carpentry,Furniture Repair,Woodwork'),
	 (64,'HVAC,AC Repair,Installation'),
	 (65,'Locksmith,Lock Repair,Security Systems'),
	 (66,'Painting,Interior Painting,Wall Finishing'),
	 (67,'Handyman,General Repairs,Maintenance'),
	 (68,'Plumbing,Emergency Repair,Leak Fixing'),
	 (69,'Electrical,Inspection,Circuit Repair'),
	 (70,'Carpentry,Modular Furniture,Installation');
INSERT INTO public.expert_expertise (expert_profile_id,expertise) VALUES
	 (71,'Plumbing,Pipeline,Drainage'),
	 (72,'Electrical,Industrial Wiring,Maintenance'),
	 (73,'Carpentry,Custom Furniture,Woodwork'),
	 (74,'HVAC,AC Maintenance,Cooling Systems'),
	 (75,'Locksmith,Emergency Unlock,Security'),
	 (76,'Painting,Decorative,Exterior Painting'),
	 (77,'Handyman,Minor Repairs,Home Fixes'),
	 (78,'Plumbing,Bathroom Fittings,Installation'),
	 (79,'Electrical,Certified Inspection,Repair'),
	 (80,'Carpentry,Office Furniture,Fittings');
INSERT INTO public.expert_expertise (expert_profile_id,expertise) VALUES
	 (81,'HVAC,Commercial Systems,Repair'),
	 (82,'Locksmith,Key Duplication,Lock Systems'),
	 (83,'Painting,Large Projects,Wall Design'),
	 (84,'Handyman,Quick Fix,General Maintenance'),
	 (85,'Plumbing,Pipeline Repair,Leak Detection'),
	 (86,'Electrical,Appliance Repair,Wiring'),
	 (87,'Carpentry,Wood Repair,Custom Work'),
	 (88,'HVAC,AC Installation,Maintenance'),
	 (89,'Locksmith,Security Locks,Installation'),
	 (90,'Painting,Interior Design,Wall Coating');
INSERT INTO public.expert_expertise (expert_profile_id,expertise) VALUES
	 (91,'Plumbing,Residential Repair,Installation'),
	 (92,'Electrical,Home Wiring,Repairs'),
	 (93,'Carpentry,Furniture Fixing,Woodwork'),
	 (94,'HVAC,System Repair,Cooling'),
	 (95,'Locksmith,Emergency Service,Unlock'),
	 (96,'Painting,Renovation,Wall Finishing'),
	 (97,'Handyman,General Service,Fixes'),
	 (98,'Plumbing,Emergency,Pipe Fix'),
	 (99,'Electrical,Technician,Circuit Repair'),
	 (100,'Carpentry,Interior Work,Wood Fix');
INSERT INTO public.expert_expertise (expert_profile_id,expertise) VALUES
	 (101,'HVAC,Repair,Maintenance'),
	 (102,'Locksmith,Home Locks,Security'),
	 (103,'Painting,Commercial,Wall Design'),
	 (104,'Handyman,Urgent Repairs,Home Service'),
	 (105,'Plumbing,Advanced Repair,Installation'),
	 (106,'Electrical,System Repair,Inspection'),
	 (107,'Carpentry,Custom Build,Furniture'),
	 (108,'HVAC,Maintenance,Cooling Systems'),
	 (109,'Locksmith,Security Systems,Locks'),
	 (110,'Painting,Interior Specialist,Decor');
INSERT INTO public.expert_expertise (expert_profile_id,expertise) VALUES
	 (111,'Plumbing,Installation,Repair'),
	 (112,'Electrical,Appliance Fix,Wiring'),
	 (113,'Carpentry,Wood Design,Furniture'),
	 (114,'HVAC,AC Service,Repair'),
	 (115,'Locksmith,Lock Fix,Security'),
	 (116,'Painting,Wall Painting,Interior'),
	 (117,'Handyman,Home Repairs,Fixing'),
	 (118,'Plumbing,Leak Repair,Drainage'),
	 (119,'Electrical,Inspection,Maintenance'),
	 (120,'Carpentry,Wood Repair,Fittings');
INSERT INTO public.expert_expertise (expert_profile_id,expertise) VALUES
	 (121,'HVAC,AC Installation,Maintenance'),
	 (122,'Locksmith,Emergency Unlock,Repair'),
	 (123,'Painting,Decorative Work,Wall Design'),
	 (124,'Handyman,Quick Service,Repairs'),
	 (125,'Plumbing,Pipeline Work,Fixing'),
	 (126,'Electrical,Wiring,System Repair'),
	 (127,'Carpentry,Custom Work,Wood Fix'),
	 (128,'HVAC,Cooling Systems,Repair'),
	 (129,'Locksmith,Security Setup,Locks'),
	 (130,'Painting,Interior Work,Finishing');
INSERT INTO public.expert_expertise (expert_profile_id,expertise) VALUES
	 (131,'Plumbing,Drainage Repair,Leak Fix'),
	 (132,'Electrical,Home Setup,Wiring'),
	 (133,'Carpentry,Furniture Build,Repair'),
	 (134,'HVAC,AC Installation,Service'),
	 (135,'Locksmith,Lock Installation,Security'),
	 (136,'Painting,Wall Coating,Interior'),
	 (137,'Handyman,General Fixes,Maintenance'),
	 (138,'Plumbing,Emergency Repair,Pipeline'),
	 (139,'Electrical,Inspection,Circuit Fix'),
	 (140,'Carpentry,Woodwork,Installation');
INSERT INTO public.expert_expertise (expert_profile_id,expertise) VALUES
	 (141,'HVAC,Maintenance,Repair'),
	 (142,'Locksmith,Unlock Services,Security'),
	 (143,'Painting,Commercial Work,Design'),
	 (144,'Handyman,Home Fix,Repairs'),
	 (145,'Plumbing,Pipeline Fix,Leak Detection'),
	 (146,'Electrical,Appliance Repair,System'),
	 (147,'Carpentry,Wood Repair,Custom'),
	 (148,'HVAC,AC Service,Installation'),
	 (149,'Locksmith,Security Locks,Repair'),
	 (150,'Painting,Decorative Walls,Interior');
INSERT INTO public.expert_expertise (expert_profile_id,expertise) VALUES
	 (151,'Plumbing,Installation,Drainage'),
	 (152,'Electrical,Wiring,Inspection'),
	 (153,'Carpentry,Furniture Fix,Woodwork'),
	 (154,'HVAC,Repair,Cooling Systems'),
	 (155,'Locksmith,Emergency Lock,Service'),
	 (156,'Painting,Renovation,Interior'),
	 (157,'Handyman,Fixes,General Service'),
	 (158,'Plumbing,Leak Fix,Repair'),
	 (159,'Electrical,Technician,System Fix'),
	 (160,'Carpentry,Wood Setup,Repair');
INSERT INTO public.expert_expertise (expert_profile_id,expertise) VALUES
	 (61,'true'),
	 (62,'true'),
	 (63,'false'),
	 (64,'true'),
	 (65,'true'),
	 (66,'false'),
	 (67,'true'),
	 (68,'true'),
	 (70,'false'),
	 (71,'true');
INSERT INTO public.expert_expertise (expert_profile_id,expertise) VALUES
	 (72,'true'),
	 (73,'false'),
	 (74,'true'),
	 (75,'true'),
	 (76,'false'),
	 (77,'true'),
	 (78,'true'),
	 (79,'true'),
	 (80,'false'),
	 (81,'true');
INSERT INTO public.expert_expertise (expert_profile_id,expertise) VALUES
	 (82,'false'),
	 (83,'true'),
	 (84,'true'),
	 (85,'false'),
	 (86,'true'),
	 (87,'true'),
	 (88,'false'),
	 (89,'true'),
	 (91,'true'),
	 (92,'false');
INSERT INTO public.expert_expertise (expert_profile_id,expertise) VALUES
	 (93,'true'),
	 (94,'true'),
	 (95,'true'),
	 (96,'false'),
	 (97,'true'),
	 (98,'true'),
	 (99,'false'),
	 (100,'true'),
	 (101,'true'),
	 (102,'true');
INSERT INTO public.expert_expertise (expert_profile_id,expertise) VALUES
	 (103,'false'),
	 (104,'true'),
	 (105,'true'),
	 (106,'false'),
	 (107,'true'),
	 (108,'true'),
	 (109,'true'),
	 (110,'false'),
	 (111,'true'),
	 (112,'false');
INSERT INTO public.expert_expertise (expert_profile_id,expertise) VALUES
	 (113,'true'),
	 (114,'true'),
	 (115,'true'),
	 (116,'false'),
	 (117,'true'),
	 (118,'true'),
	 (119,'false'),
	 (120,'true'),
	 (121,'true'),
	 (122,'true');
INSERT INTO public.expert_expertise (expert_profile_id,expertise) VALUES
	 (123,'false'),
	 (124,'true'),
	 (125,'true'),
	 (126,'false'),
	 (127,'true'),
	 (128,'true'),
	 (129,'true'),
	 (130,'false'),
	 (131,'true'),
	 (132,'false');
INSERT INTO public.expert_expertise (expert_profile_id,expertise) VALUES
	 (133,'true'),
	 (134,'true'),
	 (135,'false'),
	 (136,'true'),
	 (137,'true'),
	 (138,'false'),
	 (139,'true'),
	 (140,'true'),
	 (141,'true'),
	 (142,'false');
INSERT INTO public.expert_expertise (expert_profile_id,expertise) VALUES
	 (143,'true'),
	 (144,'true'),
	 (145,'true'),
	 (146,'false'),
	 (147,'true'),
	 (148,'true'),
	 (149,'false'),
	 (150,'true'),
	 (90,'true'),
	 (151,'true');
INSERT INTO public.expert_expertise (expert_profile_id,expertise) VALUES
	 (152,'true'),
	 (153,'false'),
	 (154,'true'),
	 (155,'true'),
	 (156,'false'),
	 (157,'true'),
	 (158,'true'),
	 (159,'true'),
	 (160,'false'),
	 (161,'true');
INSERT INTO public.expert_expertise (expert_profile_id,expertise) VALUES
	 (69,'true'),
	 (162,'true');
